#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=3:00:00,vmem=40gb
#PBS -N app-commit
#PBS -V

set -e
set -x

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

[ ! -f peaks.nii.gz ] && time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./fod_to_peaks.sh

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./reslice_wm.sh

[ ! -d COMMIT ] && time singularity exec -e docker://brainlife/commit:1.6.1 ./run_commit.py

[ ! -f streamline_weights/weights.csv ] && time singularity exec -e docker://brainlife/mrtrix3:3.0.3 ./commit2bl.sh
