#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=3:00:00,vmem=40gb
#PBS -N app-commit
#PBS -V

set -e
set -x

time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./fod_to_peaks.sh

time singularity exec -e docker://brainlife/commit ./run_commit.py

time singularity exec -e docker://brainlife/mrtrix3:3.0.3 ./commit2bl.sh
